// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/Users/jj/work/hyptpc-11.0.2/root/./BVH_3D.C";

#endif
