// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/Users/jj/work/hyptpc-11.0.2/root/rootcode/./BVH_3D_ver4.C";

#endif
